// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.72.0.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member, prefer_is_empty, unnecessary_const

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'package:uuid/uuid.dart';

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'package:uuid/uuid.dart';
import 'gen_api_1.io.dart' if (dart.library.html) 'gen_api_1.web.dart';

abstract class ApiClassOne {
  Future<bool> authenticate(
      {required String username, required String password, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kAuthenticateConstMeta;

  Future<String> getGfName({required String name, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kGetGfNameConstMeta;
}

class ApiClassOneImpl implements ApiClassOne {
  final ApiClassOnePlatform _platform;
  factory ApiClassOneImpl(ExternalLibrary dylib) =>
      ApiClassOneImpl.raw(ApiClassOnePlatform(dylib));

  /// Only valid on web/WASM platforms.
  factory ApiClassOneImpl.wasm(FutureOr<WasmModule> module) =>
      ApiClassOneImpl(module as ExternalLibrary);
  ApiClassOneImpl.raw(this._platform);
  Future<bool> authenticate(
      {required String username, required String password, dynamic hint}) {
    var arg0 = _platform.api2wire_String(username);
    var arg1 = _platform.api2wire_String(password);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_authenticate(port_, arg0, arg1),
      parseSuccessData: _wire2api_bool,
      constMeta: kAuthenticateConstMeta,
      argValues: [username, password],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kAuthenticateConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "authenticate",
        argNames: ["username", "password"],
      );

  Future<String> getGfName({required String name, dynamic hint}) {
    var arg0 = _platform.api2wire_String(name);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_get_gf_name(port_, arg0),
      parseSuccessData: _wire2api_String,
      constMeta: kGetGfNameConstMeta,
      argValues: [name],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kGetGfNameConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "get_gf_name",
        argNames: ["name"],
      );

  void dispose() {
    _platform.dispose();
  }
// Section: wire2api

  String _wire2api_String(dynamic raw) {
    return raw as String;
  }

  bool _wire2api_bool(dynamic raw) {
    return raw as bool;
  }

  int _wire2api_u8(dynamic raw) {
    return raw as int;
  }

  Uint8List _wire2api_uint_8_list(dynamic raw) {
    return raw as Uint8List;
  }
}

// Section: api2wire

@protected
int api2wire_u8(int raw) {
  return raw;
}

// Section: finalizer
