// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.72.0.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member, prefer_is_empty, unnecessary_const

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'package:uuid/uuid.dart';
import 'gen_api_authentication.dart';
export 'gen_api_authentication.dart';

class ApiAuthenticationPlatform
    extends FlutterRustBridgeBase<ApiAuthenticationWire>
    with FlutterRustBridgeSetupMixin {
  ApiAuthenticationPlatform(FutureOr<WasmModule> dylib)
      : super(ApiAuthenticationWire(dylib)) {
    setupMixinConstructor();
  }
  Future<void> setup() => inner.init;

// Section: api2wire

// Section: finalizer
}

// Section: WASM wire module

@JS('wasm_bindgen')
external ApiAuthenticationWasmModule get wasmModule;

@JS()
@anonymous
class ApiAuthenticationWasmModule implements WasmModule {
  external Object /* Promise */ call([String? moduleName]);
  external ApiAuthenticationWasmModule bind(dynamic thisArg, String moduleName);
  external dynamic /* void */ wire_divide(NativePortType port_, int a, int b);

  external dynamic /* void */ wire_multiply(NativePortType port_, int a, int b);
}

// Section: WASM wire connector

class ApiAuthenticationWire
    extends FlutterRustBridgeWasmWireBase<ApiAuthenticationWasmModule> {
  ApiAuthenticationWire(FutureOr<WasmModule> module)
      : super(WasmModule.cast<ApiAuthenticationWasmModule>(module));

  void wire_divide(NativePortType port_, int a, int b) =>
      wasmModule.wire_divide(port_, a, b);

  void wire_multiply(NativePortType port_, int a, int b) =>
      wasmModule.wire_multiply(port_, a, b);
}
